<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="26" hostname="Fatema-Kassim" failures="5" tests="5" name="Default test" time="51.325" errors="0" timestamp="2025-03-25T09:46:32 GST">
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards" time="6.409">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Register.verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards(Register.java:657)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards" time="5.761">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Register.verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards(Register.java:657)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards" time="5.511">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Register.verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards(Register.java:657)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards" time="5.164">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Register.verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards(Register.java:657)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards" time="5.218">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Register.verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards(Register.java:657)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAccountUsingPasswordsWhichAreNotFollowingPasswordComplexityStandards -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountByEnteringOnlySpaces" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountByEnteringOnlySpaces -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountByProvidingMismatchedPasswords" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountByProvidingMismatchedPasswords -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountPasswordFieldsForSecurity" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountPasswordFieldsForSecurity -->
  <testcase classname="tests.Register" name="verifyRegisterAccountPageBreadcrumbURLTitleHeading" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountPageBreadcrumbURLTitleHeading -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountWithoutSelectingPrivacyPolicyCheckboxField" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountWithoutSelectingPrivacyPolicyCheckboxField -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingMandatoryFields" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountUsingMandatoryFields -->
  <testcase classname="tests.Register" name="verifyRegistringAccountUsingAllFields" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegistringAccountUsingAllFields -->
  <testcase classname="tests.Register" name="verifyThankYourConfirmationEmailOnSuccessfulRegistration" time="0.0">
    <ignored/>
  </testcase> <!-- verifyThankYourConfirmationEmailOnSuccessfulRegistration -->
  <testcase classname="tests.Register" name="verifyDifferentWaysOfNavigatingToRegisterAccountPage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDifferentWaysOfNavigatingToRegisterAccountPage -->
  <testcase classname="tests.Register" name="verifyRegisterAccountPageNavigations" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountPageNavigations -->
  <testcase classname="tests.Register" name="verifyDataBaseTestingForRegisterAccount" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDataBaseTestingForRegisterAccount -->
  <testcase classname="tests.Register" name="verifyRegisterAccountInAllEnvironments" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountInAllEnvironments -->
  <testcase classname="tests.Register" name="verifyRegisterAccountPagePlaceholders" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountPagePlaceholders -->
  <testcase classname="tests.Register" name="verifyRegisterAccountUsingLeadingAndTrailingSpaces" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountUsingLeadingAndTrailingSpaces -->
  <testcase classname="tests.Register" name="verifyRegisterAccountWithExistingEmailAddress" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountWithExistingEmailAddress -->
  <testcase classname="tests.Register" name="verifyMandatoryFieldsInRegisterAccountPage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyMandatoryFieldsInRegisterAccountPage -->
  <testcase classname="tests.Register" name="verifyRegisterAccountPrivacyPolicyField" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountPrivacyPolicyField -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountBySubscribingToNewsletter" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountBySubscribingToNewsletter -->
  <testcase classname="tests.Register" name="verifyWarningMessageOfMandatoryFieldsInRegisterAccountPage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyWarningMessageOfMandatoryFieldsInRegisterAccountPage -->
  <testcase classname="tests.Register" name="verifyRegisterAccountUI" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterAccountUI -->
  <testcase classname="tests.Register" name="verifyHeightWidthNumberOfCharacters" time="0.0">
    <ignored/>
  </testcase> <!-- verifyHeightWidthNumberOfCharacters -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingInvalidEmail" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountUsingInvalidEmail -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingKeyboardKeys" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountUsingKeyboardKeys -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountByNotSubscribingToNewsletter" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountByNotSubscribingToNewsletter -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountWithoutEnteringConfirmationPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountWithoutEnteringConfirmationPassword -->
  <testcase classname="tests.Register" name="verifyRegisteringAccountUsingInvalidTelephoneNumber" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAccountUsingInvalidTelephoneNumber -->
</testsuite> <!-- Default test -->
